# localization.py
# -*- coding: utf-8 -*-

TRANSLATIONS = {
    "en": {
        "window_title": "Scroll Lock Settings",
        "tab_general": "General",
        "tab_sensitivity": "Sensitivity",
        "tab_apps": "Apps & Profiles",
        "grp_blocking": "Blocking Logic",
        "grp_adv_features": "Advanced Features",
        "grp_app_control": "Application Control",
        "grp_general": "General Settings",
        "grp_system": "System",
        "grp_info": "Info",
        "lbl_language": "Language / Dil:",
        "chk_start_boot": "Start on boot",
        "tip_start_boot": "If checked, the application will start automatically when Windows boots.",
        "chk_enable": "Enable Scroll Blocking",
        "tip_enable": "Master switch to enable or disable the scroll blocking functionality.",
        "lbl_font_size": "Font Size:",
        "tip_font_size": "Adjust the global font size for the application UI.",
        "lbl_interval": "Block interval (s):",
        "tip_interval": "The time window (seconds) to block rapid direction changes.",
        "lbl_threshold": "Direction threshold:",
        "tip_threshold": "Number of opposite ticks required to confirm a new direction.",
        "lbl_min_reversal": "Min Reversal Time (s):",
        "tip_min_reversal": "Physics Check: Impossible reversals faster than this are blocked instantly.",
        "chk_strict": "Strict Mode (Ignores first tick)",
        "tip_strict": "Require two consecutive scrolls to start. Prevents initial jitter.",
        "chk_smart": "Smart Momentum (Dynamic)",
        "tip_smart": "Automatically increases threshold when scrolling very fast.",
        "lbl_blacklist": "Blacklist (Blocking Disabled):",
        "btn_add_current": "Add Current App",
        "btn_remove_selected": "Remove Selected",
        "btn_clear_all": "Clear All",
        "lbl_profiles": "Custom Profiles:",
        "btn_add_profile": "Add Profile",
        "btn_edit_profile": "Edit Profile",
        "btn_remove_profile": "Remove Profile",
        "btn_calibration": "Calibration Wizard",
        "btn_defaults": "Restore Defaults",
        "btn_save": "Save Changes",
        "btn_website": "Visit Website",
        "status_saved": "Settings saved successfully.",
        "status_restored": "Restored to defaults successfully.",
        "msg_unsaved_title": "Unsaved Changes",
        "msg_unsaved_text": "You have unsaved changes. Do you want to save them?",
        "msg_input_error": "Input Error",
        "msg_empty_name": "Application name cannot be empty.",
        "msg_select_profile": "Please select a profile.",
        "msg_confirm_removal": "Are you sure you want to remove the selected profile(s)?",
        "msg_calib_complete": "Calibration Complete",
        "msg_calib_text": "Settings have been optimized for your mouse!",
        "msg_reset_title": "Confirm Reset",
        "msg_reset_text": "Are you sure you want to restore the default settings?",
        "tray_settings": "Settings",
        "tray_toggle": "Toggle Scroll Blocking",
        "tray_help": "Help",
        "tray_about": "About",
        "tray_exit": "Exit",
        "tray_msg_title": "Scroll Blocking",
        "tray_enabled": "Enabled",
        "tray_disabled": "Disabled",
        
        # Calibration Wizard
        "calib_window_title": "Ultimate Calibration Suite",
        "calib_mode_header": "CALIBRATION MODE",
        "calib_suite_header": "CALIBRATION SUITE",
        "calib_intro_instr": "We will record your raw mouse input to detect hardware faults.<br>Follow the animated guide.",
        "calib_btn_abort": "Abort",
        "calib_btn_start": "Start Calibration",
        "calib_btn_next_phase": "Next Phase ->",
        "calib_btn_apply_settings": "Apply These Settings",
        "calib_stage_complete": "Stage Complete",
        "calib_prepare_next": "Prepare for the next phase.",
        
        "calib_phase1_title": "Phase 1: The Flow",
        "calib_phase1_instr": "Scroll <b>DOWN</b> continuously.<br>Aim for a smooth, steady rhythm.",
        "calib_phase2_title": "Phase 2: The Sprint",
        "calib_phase2_instr": "Scroll <b>DOWN</b> as FAST as possible!<br>Keep it up for 10 seconds!",
        "calib_phase3_title": "Phase 3: The Brake",
        "calib_phase3_instr": "Scroll <b>DOWN</b> fast...<br>When you see <b>STOP</b>, let go immediately!",
        "calib_phase4_title": "Phase 4: Precision",
        "calib_phase4_instr": "Scroll <b>UP</b> slowly, one tick at a time.<br>Be precise.",
        "calib_phase_analysis": "Analysis",
        "calib_phase_processing": "Processing data...",
        
        "calib_stop_signal": "STOP!!! Do not touch the wheel!",
        "calib_scroll_down_again": "Scroll <b>DOWN</b> fast again...",
        
        "calib_analysis_report": "Analysis Report",
        "calib_diag_header": "Diagnosis:",
        "calib_diag_fast_reversals": "Detected {count} fast reversals (min {min_ms}ms). Physics check optimized.",
        "calib_diag_signal_high_consistency": "Signal consistency is high during steady scrolling.",
        "calib_diag_high_scroll_velocity": "User has high scroll velocity. Smart Momentum enabled.",
        "calib_diag_stop_bounce": "Stop bounce detected (worst latency: {worst_ms}ms). Interval adjusted.",
        "calib_diag_no_bounce": "No bounce-back detected on stop. Clean mechanicals.",
        "calib_diag_optimized_interval": "Interval adjusted.",
        "calib_diag_optimized_threshold": "Threshold adjusted.",
        "calib_diag_optimized_strict": "Strict Mode enabled.",
        "calib_diag_optimized_physics": "Physics check optimized.",
        "calib_diag_optimized_smart": "Smart Momentum enabled.",
        
        "calib_table_interval": "Block Interval:",
        "calib_table_threshold": "Threshold:",
        "calib_table_strict": "Strict Mode:",
        "calib_table_physics": "Physics Check:",
        "calib_table_smart": "Smart Momentum:"
    },
    "tr": {
        "window_title": "Scroll Lock Ayarları",
        "tab_general": "Genel",
        "tab_sensitivity": "Hassasiyet",
        "tab_apps": "Uygulamalar & Profiller",
        "grp_blocking": "Engelleme Mantığı",
        "grp_adv_features": "Gelişmiş Özellikler",
        "grp_app_control": "Uygulama Kontrolü",
        "grp_general": "Genel Ayarlar",
        "grp_system": "Sistem",
        "grp_info": "Bilgi",
        "lbl_language": "Dil / Language:",
        "chk_start_boot": "Bilgisayar açılınca başlat",
        "tip_start_boot": "İşaretlenirse, Windows başladığında uygulama otomatik çalışır.",
        "chk_enable": "Kaydırma Engelleyiciyi Aç",
        "tip_enable": "Kaydırma engelleme işlevini açıp kapatan ana şalter.",
        "lbl_font_size": "Yazı Boyutu:",
        "tip_font_size": "Uygulama arayüzünün yazı boyutunu ayarlar.",
        "lbl_interval": "Blok Aralığı (sn):",
        "tip_interval": "Ani yön değişimlerinin engelleneceği zaman penceresi.",
        "lbl_threshold": "Yön Eşiği (Tık):",
        "tip_threshold": "Yeni bir yöne gitmek için gereken ardışık tık sayısı.",
        "lbl_min_reversal": "Min Ters Dönüş (sn):",
        "tip_min_reversal": "Fizik Kontrolü: Bu süreden hızlı gerçekleşen ters hareketler gürültü sayılır.",
        "chk_strict": "Katı Mod (İlk tıkı yutar)",
        "tip_strict": "Başlamak için iki ardışık tık gerektirir. İlk sıçramayı önler.",
        "chk_smart": "Akıllı Momentum (Dinamik)",
        "tip_smart": "Hızlı kaydırırken eşik değerini otomatik artırır.",
        "lbl_blacklist": "Kara Liste (Engelleme Kapalı):",
        "btn_add_current": "Şu Anki Uygulamayı Ekle",
        "btn_remove_selected": "Seçileni Kaldır",
        "btn_clear_all": "Hepsini Temizle",
        "lbl_profiles": "Özel Profiller:",
        "btn_add_profile": "Profil Ekle",
        "btn_edit_profile": "Düzenle",
        "btn_remove_profile": "Kaldır",
        "btn_calibration": "Kalibrasyon Sihirbazı",
        "btn_defaults": "Varsayılanları Yükle",
        "btn_save": "Değişiklikleri Kaydet",
        "btn_website": "Web Sitesi",
        "status_saved": "Ayarlar başarıyla kaydedildi.",
        "status_restored": "Varsayılan ayarlara dönüldü.",
        "msg_unsaved_title": "Kaydedilmemiş Değişiklikler",
        "msg_unsaved_text": "Kaydedilmemiş değişiklikler var. Kaydetmek ister misin?",
        "msg_input_error": "Girdi Hatası",
        "msg_empty_name": "Uygulama adı boş olamaz.",
        "msg_select_profile": "Lütfen bir profil seçin.",
        "msg_confirm_removal": "Seçili profili silmek istediğine emin misin?",
        "msg_calib_complete": "Kalibrasyon Tamamlandı",
        "msg_calib_text": "Ayarlar fareniz için optimize edildi!",
        "msg_reset_title": "Sıfırlama Onayı",
        "msg_reset_text": "Varsayılan ayarlara dönmek istediğine emin misin?",
        "tray_settings": "Ayarlar",
        "tray_toggle": "Engellemeyi Aç/Kapat",
        "tray_help": "Yardım",
        "tray_about": "Hakkında",
        "tray_exit": "Çıkış",
        "tray_msg_title": "Kaydırma Engelleme",
        "tray_enabled": "Aktif",
        "tray_disabled": "Devre Dışı",

        # Kalibrasyon Sihirbazı
        "calib_window_title": "Gelişmiş Kalibrasyon Aracı",
        "calib_mode_header": "KALİBRASYON MODU",
        "calib_suite_header": "KALİBRASYON PAKETİ",
        "calib_intro_instr": "Donanım hatalarını tespit etmek için fare girişinizi kaydedeceğiz.<br>Animasyonlu rehberi takip edin.",
        "calib_btn_abort": "İptal",
        "calib_btn_start": "Kalibrasyonu Başlat",
        "calib_btn_next_phase": "Sonraki Aşama ->",
        "calib_btn_apply_settings": "Bu Ayarları Uygula",
        "calib_stage_complete": "Aşama Tamamlandı",
        "calib_prepare_next": "Sonraki aşamaya hazırlanın.",
        
        "calib_phase1_title": "Aşama 1: Akış",
        "calib_phase1_instr": "Sürekli olarak <b>AŞAĞI</b> kaydırın.<br>Düzgün, istikrarlı bir ritim hedefleyin.",
        "calib_phase2_title": "Aşama 2: Sprint",
        "calib_phase2_instr": "Mümkün olduğunca HIZLI bir şekilde <b>AŞAĞI</b> kaydırın!<br>10 saniye boyunca devam edin!",
        "calib_phase3_title": "Aşama 3: Fren",
        "calib_phase3_instr": "Hızlıca <b>AŞAĞI</b> kaydırın...<br><b>DUR</b> yazısını görünce hemen bırakın!",
        "calib_phase4_title": "Aşama 4: Hassasiyet",
        "calib_phase4_instr": "Yavaşça, tek tıkla <b>YUKARI</b> kaydırın.<br>Hassas olun.",
        "calib_phase_analysis": "Analiz",
        "calib_phase_processing": "Veriler işleniyor...",
        
        "calib_stop_signal": "DUR!!! Tekerleğe dokunmayın!",
        "calib_scroll_down_again": "Tekrar hızlıca <b>AŞAĞI</b> kaydırın...",
        
        "calib_analysis_report": "Analiz Raporu",
        "calib_diag_header": "Teşhis:",
        "calib_diag_fast_reversals": "{count} hızlı ters hareket tespit edildi (min {min_ms}ms). Fizik kontrolü optimize edildi.",
        "calib_diag_signal_high_consistency": "Sabit kaydırma sırasında sinyal tutarlılığı yüksek.",
        "calib_diag_high_scroll_velocity": "Kullanıcının kaydırma hızı yüksek. Akıllı Momentum etkinleştirildi.",
        "calib_diag_stop_bounce": "Duruşta sıçrama tespit edildi (en kötü gecikme: {worst_ms}ms). Aralık ayarlandı.",
        "calib_diag_no_bounce": "Duruşta sıçrama tespit edilmedi. Temiz mekanik.",
        "calib_diag_optimized_interval": "Aralık ayarlandı.",
        "calib_diag_optimized_threshold": "Eşik ayarlandı.",
        "calib_diag_optimized_strict": "Katı Mod etkinleştirildi.",
        "calib_diag_optimized_physics": "Fizik kontrolü optimize edildi.",
        "calib_diag_optimized_smart": "Akıllı Momentum etkinleştirildi.",
        
        "calib_table_interval": "Blok Aralığı:",
        "calib_table_threshold": "Eşik:",
        "calib_table_strict": "Katı Mod:",
        "calib_table_physics": "Fizik Kontrolü:",
        "calib_table_smart": "Akıllı Momentum:"
    }
}

class Translator:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(Translator, cls).__new__(cls)
            cls._instance.language = "en"
        return cls._instance

    def set_language(self, lang_code):
        if lang_code in TRANSLATIONS:
            self.language = lang_code

    def get_language(self):
        return self.language

    def tr(self, key, **kwargs):
        """Returns the translated string for the given key, with optional formatting."""
        lang_dict = TRANSLATIONS.get(self.language, TRANSLATIONS["en"])
        translated_text = lang_dict.get(key, key)
        return translated_text.format(**kwargs)

translator = Translator() # Global instance
